[package]
name = "sdl_simple"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
gl = "0.14.0"
cgmath = "0.17.0"
c_str_macro = "1.0.2"
